### ISSUE TITLE
upgrade to djl 0.16

### ISSUE THREAD

**Issue by behrica** [scicloj/scicloj.ml.clj-djl#5]

**Comment by kimim** [comment]
I update to djl 0.16.0 in clj-djl 0.1.9, may I change 
`org.clojars.behrica/clj-djl        {:mvn/version "0.1.8"}`
to 
`cjl-djl/clj-djl        {:mvn/version "0.1.9"}`?

**Comment by behrica** [comment]
I looked into this, and noticed that the fasttext API has changed and I have it craching consistently with fasttext

**Comment by behrica** [comment]
I find text fasttext support in here important,
https://github.com/scicloj/scicloj.ml.clj-djl/blob/master/src/scicloj/ml/clj_djl/fasttext.clj

as it brings a very good text classification to Clojure.

But as I said, I could not get it working. I adapted the code to the new API in 

```clojure
ai.djl.fasttext/fasttext-engine    {:mvn/version "0.16.0"}
```
but it keeps crashing in native code even with the "simplest code", and I am not sure how do debug it.

**Comment by kimim** [comment]
It seems unit tests are all passed.

**Comment by behrica** [comment]
With 0.15 yes.
The moment I switch to 0.16, I need to change the fasttext related code, here:
https://github.com/scicloj/scicloj.ml.clj-djl/blob/master/src/scicloj/ml/clj_djl/fasttext.clj
The api has changed in an incompatibe way between 0.15 and 0.16:
https://javadoc.io/doc/ai.djl.fasttext/fasttext-engine/0.16.0/index.html
Doing so, makes even the the simplest fasttext code crash.

But I just saw that 0.17 was released, I will try it

**Comment by behrica** [comment]
djl 0.17 solved the problem wit fasttext. Changed is push into master
